"""add health check observations and observation evidence

Revision ID: b429d6e5dea0
Revises: bc15717fef85
Create Date: 2026-03-03 00:25:32.805452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b429d6e5dea0'
down_revision: Union[str, None] = 'bc15717fef85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_control_observations',
    sa.Column('session_control_instance_id', sa.Uuid(), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_control_instance_id'], ['session_control_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_control_observation_evidence',
    sa.Column('session_control_observation_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_control_observation_id'], ['session_control_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('session_control_instances', sa.Column('assessment_checklist_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_control_instances', 'assessment_checklist_snapshot')
    op.drop_table('session_control_observation_evidence')
    op.drop_table('session_control_observations')
    # ### end Alembic commands ###
