"""add requirement testing procedure and checkpoint snapshots to session control instances

Revision ID: bc15717fef85
Revises: 8273559e2bc1
Create Date: 2026-03-03 00:05:21.373914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc15717fef85'
down_revision: Union[str, None] = '8273559e2bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_project_members_project_user'), 'project_members', type_='unique')
    op.add_column('session_control_instances', sa.Column('requirements_text_snapshot', sa.Text(), nullable=True))
    op.add_column('session_control_instances', sa.Column('testing_procedures_text_snapshot', sa.Text(), nullable=True))
    op.add_column('session_control_instances', sa.Column('check_points_text_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_control_instances', 'check_points_text_snapshot')
    op.drop_column('session_control_instances', 'testing_procedures_text_snapshot')
    op.drop_column('session_control_instances', 'requirements_text_snapshot')
    op.create_unique_constraint(op.f('uq_project_members_project_user'), 'project_members', ['project_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
